### ISSUE TITLE
Proper Config File

### ISSUE THREAD

**Issue by jlevesy** [jlevesy/kudo#50]
### What needs to be done?

Kudo at the moment ~~hardcodes stuff~~ does not offer any opportunity to configure its internal behavior. 

It would be nice to introduce a config map, instead of flags. For instance to allow the following properties to be configured

- resyncInterval
- retryInterval
- threadiness
- Audit Sinks

```yaml
resyncInterval: 30s
retryInterval: 10s
threadiness: 10
auditSinks:
   - kind: K8sEvents
     namespace: ""
```
